# This is a basic workflow to help you get started with Actions

name: deploy Azure sa

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore: 
        - "*.ps1"
        - ".github/workflows/*"
  
  workflow_dispatch:

env: 
  RG_Name: RG10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run linter on bicep
        run: az bicep build --file storage.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        name: sign in to Azure
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - uses: azure/cli@v1
        name: create RG
        with:
          inlineScript: az group create --location WestEurope --name ${{env.RG_Name}}
      
      - uses: azure/arm-deploy@v1
        name: deploy sa
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.RG_Name}}
          template: ./storage.bicep

      - uses: azure/arm-deploy@v1
        name: deploy sa container
        id: deploy-sa-container
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.RG_Name}}
          template: ./blobcontainer.bicep
          parameters: mysaname=${{steps.deploy-sa.outputs.mysaname}}
